name: nfl_survival
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Runtime dependencies
  hooks_riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.4
  dio: ^5.9.0
  retrofit: ^4.7.2
  http: ^1.2.2
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_hooks: ^0.21.3+1
  flutter_dotenv: ^6.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  cached_network_image: ^3.3.1
  html: ^0.15.4
  google_mobile_ads: ^5.1.0
  
  # Supabase
  supabase_flutter: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints and codegen
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  retrofit_generator: ^10.0.5

  # Testing
  mocktail: ^1.0.4
  mockito: ^5.4.4
  riverpod_test: ^0.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/mock/
