[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && ./start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
