// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa2IdzHI5InM4-ZmpOfFr4sldbyvYbfyM',
    appId: '1:95620296373:web:d0d3803d7b9d46ef9398fc',
    messagingSenderId: '95620296373',
    projectId: 'pick1-34708',
    authDomain: 'pick1-34708.firebaseapp.com',
    storageBucket: 'pick1-34708.firebasestorage.app',
    measurementId: 'G-32ZMCYRYZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa2IdzHI5InM4-ZmpOfFr4sldbyvYbfyM',
    appId: '1:95620296373:android:d0d3803d7b9d46ef9398fc',
    messagingSenderId: '95620296373',
    projectId: 'pick1-34708',
    storageBucket: 'pick1-34708.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa2IdzHI5InM4-ZmpOfFr4sldbyvYbfyM',
    appId: '1:95620296373:ios:d0d3803d7b9d46ef9398fc',
    messagingSenderId: '95620296373',
    projectId: 'pick1-34708',
    storageBucket: 'pick1-34708.firebasestorage.app',
    iosBundleId: 'com.example.nflSurvival',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa2IdzHI5InM4-ZmpOfFr4sldbyvYbfyM',
    appId: '1:95620296373:ios:d0d3803d7b9d46ef9398fc',
    messagingSenderId: '95620296373',
    projectId: 'pick1-34708',
    storageBucket: 'pick1-34708.firebasestorage.app',
    iosBundleId: 'com.example.nflSurvival',
  );
}
