import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:nfl_survival/app/providers.dart';
import 'package:nfl_survival/data/models/league.dart';
import 'package:nfl_survival/widgets/app_scaffold.dart';
import 'package:nfl_survival/widgets/banner_ad_slot.dart';

final userLeaguesProvider = FutureProvider<List<League>>((ref) async {
  final currentUser = await ref.watch(currentUserProvider.future);
  if (currentUser == null) return [];
  return ref.read(leagueRepositoryProvider).listLeaguesForUser(currentUser.id);
});

class LeagueListScreen extends ConsumerWidget {
  const LeagueListScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final leaguesAsync = ref.watch(userLeaguesProvider);
    final currentUserAsync = ref.watch(currentUserProvider);
    final isPremium = ref.watch(premiumStatusProvider).valueOrNull ?? false;

    return AppScaffold(
      appBar: AppBar(title: const Text('My Leagues')),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          final currentUser = currentUserAsync.value;
          if (currentUser != null && !isPremium && currentUser.joinedLeagueIds.isNotEmpty) {
            context.go('/paywall');
            return;
          }

          // For freemium, create a basic league. Premium can customize.
          final newLeague = League(
            id: '', // Will be generated by repository
            name: 'My New League ${DateTime.now().year}',
            ownerId: currentUser!.id,
            visibility: LeagueVisibility.PRIVATE,
            settings: isPremium
                ? const LeagueSettings(
                    maxLosses: 1,
                    allowTeamReuse: true,
                    autoEliminateOnNoPick: false,
                    minTeams: 4,
                    tiebreaker: Tiebreaker.MOST_REMAINING_TEAMS,
                  )
                : const LeagueSettings(
                    maxLosses: 0,
                    allowTeamReuse: false,
                    autoEliminateOnNoPick: true,
                    minTeams: 2,
                    tiebreaker: Tiebreaker.LAST_LONGEST_STREAK,
                  ),
            season: 2025, // Mock season
            createdAtIso: DateTime.now().toIso8601String(),
            memberIds: [currentUser.id],
          );
          final createdLeague = await ref.read(leagueRepositoryProvider).createLeague(newLeague);
          // Update user's joined leagues
          final updatedUser = currentUser.copyWith(
            joinedLeagueIds: [...currentUser.joinedLeagueIds, createdLeague.id],
          );
          // This is a mock update, in a real app, this would be handled by the AuthRepository
          // For now, we'll just refresh the current user provider
          ref.invalidate(currentUserProvider);
          context.go('/league/${createdLeague.id}');
        },
        child: const Icon(Icons.add),
      ),
      child: Column(
        children: [
          Expanded(
            child: leaguesAsync.when(
              data: (leagues) {
                if (leagues.isEmpty) {
                  return const Center(child: Text('No leagues joined. Create one!'));
                }
                return ListView.builder(
                  itemCount: leagues.length,
                  itemBuilder: (context, index) {
                    final league = leagues[index];
                    return ListTile(
                      title: Text(league.name),
                      subtitle: Text('Season: ${league.season} | Members: ${league.memberIds.length}'),
                      onTap: () => context.go('/league/${league.id}'),
                    );
                  },
                );
              },
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (e, st) => Center(child: Text('Error: $e')),
            ),
          ),
          if (!isPremium) const BannerAdSlot(),
        ],
      ),
    );
  }
}
