name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: dart run build_runner build -d
      - run: dart format --set-exit-if-changed .
      - run: flutter analyze
      - run: flutter test --no-pub

